services:
  postgres:
    image: postgres:15
    container_name: jurisprudencia_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}         
      POSTGRES_USER: ${DB_USER}        
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jurisprudencia_network

  redis:
    image: redis:7-alpine
    container_name: jurisprudencia_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - jurisprudencia_network

volumes:
  postgres_data:
  redis_data:

networks:
  jurisprudencia_network:
    driver: bridge
